package com.navalarmament.init;

import com.navalarmament.block.common.BlockAmmoStorage;
import com.navalarmament.block.common.BlockElevator;
import com.navalarmament.block.common.BlockHullPanel;
import com.navalarmament.block.common.BlockHullStructure;
import com.navalarmament.block.common.BlockNavalCable;
import com.navalarmament.block.common.BlockNavalDummy;
import com.navalarmament.block.common.BlockShutter;
import com.navalarmament.block.common.BlockSubmarineEquip;
import com.navalarmament.block.common.BlockWeaponElevator;
import com.navalarmament.block.usn.*;
import com.navalarmament.tileentity.common.*;
import com.navalarmament.tileentity.usn.*;
import cpw.mods.fml.common.registry.GameRegistry;

public class NavalBlocks {

    public static BlockNavalDummy      NAVAL_DUMMY;
    public static BlockNavalCable      NAVAL_CABLE;
    public static BlockSPY1Radar       SPY1_RADAR;
    public static BlockSPS67Radar      SPS67_RADAR;
    public static BlockSQS53Sonar      SQS53_SONAR;
    public static BlockCandD           CANDD;
    public static BlockWCS             WCS;
    public static BlockADS             ADS;
    public static BlockDataLink        DATALINK;
    public static BlockAuxProcessor    AUX_PROCESSOR;
    public static BlockMk45Gun         MK45_GUN;
    public static BlockMk38Gun         MK38_GUN;
    public static BlockMk41VLS8        MK41_VLS_8;
    public static BlockMk41VLS16       MK41_VLS_16;
    public static BlockMk41VLS32       MK41_VLS_32;
    public static BlockMk41VLS64       MK41_VLS_64;
    public static BlockPhalanxCIWS     PHALANX_CIWS;
    public static BlockSPG62           SPG62;
    public static BlockHarpoonLauncher HARPOON_LAUNCHER;
    public static BlockMk32Torpedo     MK32_TORPEDO;
    public static BlockSubTorpedo      SUB_TORPEDO;
    public static BlockSubVLS8         SUB_VLS_8;
    public static BlockSubVLS16        SUB_VLS_16;
    public static BlockSubVLSSSBN8     SUB_VLS_SSBN_8;
    public static BlockSubVLSSSBN16    SUB_VLS_SSBN_16;
    public static BlockSubVLSSSGN8     SUB_VLS_SSGN_8;
    public static BlockSubVLSSSGN16    SUB_VLS_SSGN_16;
    public static BlockLargeDisplay    LARGE_DISPLAY;
    public static BlockOperatorConsole OPERATOR_CONSOLE;
    public static BlockCICDecoration   CIC_DECORATION;
    public static BlockIFLOLS          IFLOLS;
    public static BlockShutter         SHUTTER;
    public static BlockElevator        ELEVATOR;
    public static BlockWeaponElevator  WEAPON_ELEVATOR;
    public static BlockCatapult        CATAPULT;
    public static BlockArrestingWire   ARRESTING_WIRE;
    public static BlockHullPanel       HULL_PANEL;
    public static BlockHullStructure   HULL_STRUCTURE;
    public static BlockSubmarineEquip  SUBMARINE_EQUIP;
    public static BlockAmmoStorage     AMMO_STORAGE;

    public static void register() {
        NAVAL_DUMMY      = reg(new BlockNavalDummy(),      "naval_dummy");
        GameRegistry.registerTileEntity(TENavalDummy.class,       "naval_dummy_te");
        NAVAL_CABLE      = reg(new BlockNavalCable(),      "naval_cable");
        GameRegistry.registerTileEntity(TENavalCable.class,       "naval_cable_te");
        SPY1_RADAR       = reg(new BlockSPY1Radar(),       "spy1_radar");
        GameRegistry.registerTileEntity(TESPY1Radar.class,        "spy1_radar_te");
        SPS67_RADAR      = reg(new BlockSPS67Radar(),      "sps67_radar");
        GameRegistry.registerTileEntity(TEPS67Radar.class,        "sps67_radar_te");
        SQS53_SONAR      = reg(new BlockSQS53Sonar(),      "sqs53_sonar");
        GameRegistry.registerTileEntity(TESQS53Sonar.class,       "sqs53_sonar_te");
        CANDD            = reg(new BlockCandD(),           "candd");
        GameRegistry.registerTileEntity(TECandD.class,            "candd_te");
        WCS              = reg(new BlockWCS(),             "wcs");
        GameRegistry.registerTileEntity(TEWCS.class,              "wcs_te");
        ADS              = reg(new BlockADS(),             "ads");
        GameRegistry.registerTileEntity(TEADS.class,              "ads_te");
        DATALINK         = reg(new BlockDataLink(),        "datalink");
        GameRegistry.registerTileEntity(TEDataLink.class,         "datalink_te");
        AUX_PROCESSOR    = reg(new BlockAuxProcessor(),    "aux_processor");
        GameRegistry.registerTileEntity(TEAuxProcessor.class,     "aux_processor_te");
        MK45_GUN         = reg(new BlockMk45Gun(),         "mk45_gun");
        GameRegistry.registerTileEntity(TEMk45Gun.class,          "mk45_gun_te");
        MK38_GUN         = reg(new BlockMk38Gun(),         "mk38_gun");
        GameRegistry.registerTileEntity(TEMk38Gun.class,          "mk38_gun_te");
        MK41_VLS_8       = reg(new BlockMk41VLS8(),        "mk41_vls_8");
        GameRegistry.registerTileEntity(TEMk41VLS8.class,         "mk41_vls_8_te");
        MK41_VLS_16      = reg(new BlockMk41VLS16(),       "mk41_vls_16");
        GameRegistry.registerTileEntity(TEMk41VLS16.class,        "mk41_vls_16_te");
        MK41_VLS_32      = reg(new BlockMk41VLS32(),       "mk41_vls_32");
        GameRegistry.registerTileEntity(TEMk41VLS32.class,        "mk41_vls_32_te");
        MK41_VLS_64      = reg(new BlockMk41VLS64(),       "mk41_vls_64");
        GameRegistry.registerTileEntity(TEMk41VLS64.class,        "mk41_vls_64_te");
        PHALANX_CIWS     = reg(new BlockPhalanxCIWS(),     "phalanx_ciws");
        GameRegistry.registerTileEntity(TEPhalanxCIWS.class,      "phalanx_ciws_te");
        SPG62            = reg(new BlockSPG62(),           "spg62");
        GameRegistry.registerTileEntity(TESPG62.class,            "spg62_te");
        HARPOON_LAUNCHER = reg(new BlockHarpoonLauncher(), "harpoon_launcher");
        GameRegistry.registerTileEntity(TEHarpoonLauncher.class,  "harpoon_launcher_te");
        MK32_TORPEDO     = reg(new BlockMk32Torpedo(),     "mk32_torpedo");
        GameRegistry.registerTileEntity(TEMk32Torpedo.class,      "mk32_torpedo_te");
        SUB_TORPEDO      = reg(new BlockSubTorpedo(),      "sub_torpedo");
        GameRegistry.registerTileEntity(TESubTorpedo.class,       "sub_torpedo_te");
        SUB_VLS_8        = reg(new BlockSubVLS8(),         "sub_vls_8");
        GameRegistry.registerTileEntity(TESubVLS8.class,          "sub_vls_8_te");
        SUB_VLS_16       = reg(new BlockSubVLS16(),        "sub_vls_16");
        GameRegistry.registerTileEntity(TESubVLS16.class,         "sub_vls_16_te");
        SUB_VLS_SSBN_8   = reg(new BlockSubVLSSSBN8(),     "sub_vls_ssbn_8");
        GameRegistry.registerTileEntity(TESubVLSSSBN8.class,      "sub_vls_ssbn_8_te");
        SUB_VLS_SSBN_16  = reg(new BlockSubVLSSSBN16(),    "sub_vls_ssbn_16");
        GameRegistry.registerTileEntity(TESubVLSSSBN16.class,     "sub_vls_ssbn_16_te");
        SUB_VLS_SSGN_8   = reg(new BlockSubVLSSSGN8(),     "sub_vls_ssgn_8");
        GameRegistry.registerTileEntity(TESubVLSSSGN8.class,      "sub_vls_ssgn_8_te");
        SUB_VLS_SSGN_16  = reg(new BlockSubVLSSSGN16(),    "sub_vls_ssgn_16");
        GameRegistry.registerTileEntity(TESubVLSSSGN16.class,     "sub_vls_ssgn_16_te");
        LARGE_DISPLAY    = reg(new BlockLargeDisplay(),    "large_display");
        GameRegistry.registerTileEntity(TELargeDisplay.class,     "large_display_te");
        OPERATOR_CONSOLE = reg(new BlockOperatorConsole(), "operator_console");
        GameRegistry.registerTileEntity(TEOperatorConsole.class,  "operator_console_te");
        CIC_DECORATION   = reg(new BlockCICDecoration(),   "cic_decoration");
        IFLOLS           = reg(new BlockIFLOLS(),          "iflols");
        GameRegistry.registerTileEntity(TEIFLOLS.class,           "iflols_te");
        SHUTTER          = reg(new BlockShutter(),         "shutter");
        GameRegistry.registerTileEntity(TEShutter.class,          "shutter_te");
        ELEVATOR         = reg(new BlockElevator(),        "elevator");
        GameRegistry.registerTileEntity(TEElevator.class,         "elevator_te");
        WEAPON_ELEVATOR  = reg(new BlockWeaponElevator(),  "weapon_elevator");
        GameRegistry.registerTileEntity(TEWeaponElevator.class,   "weapon_elevator_te");
        CATAPULT         = reg(new BlockCatapult(),        "catapult");
        GameRegistry.registerTileEntity(TECatapult.class,         "catapult_te");
        ARRESTING_WIRE   = reg(new BlockArrestingWire(),   "arresting_wire");
        GameRegistry.registerTileEntity(TEArrestingWire.class,    "arresting_wire_te");
        HULL_PANEL       = reg(new BlockHullPanel(),       "hull_panel");
        HULL_STRUCTURE   = reg(new BlockHullStructure(),   "hull_structure");
        SUBMARINE_EQUIP  = reg(new BlockSubmarineEquip(),  "submarine_equip");
        AMMO_STORAGE     = reg(new BlockAmmoStorage(),     "ammo_storage");
        GameRegistry.registerTileEntity(TEAmmoStorage.class,      "ammo_storage_te");
    }

    private static <T extends net.minecraft.block.Block> T reg(T block, String name) {
        GameRegistry.registerBlock(block, name);
        return block;
    }
}